# BEA 2-way generator

An attempt at tidying the code up at least a little so that eg. Aisling has a fighting chance of seeing what it's even doing.

**Convert the raw cells to Python to check the functions are working OK**

The core aspect is the call to `amati_bea.induce_theory`, and we can then write the theory to a file. The rules will come from `clingo_program_files/bea_rules.amati`.

There's a number of legacy imports here.

In [1]:
import amati_bea as amati

In [2]:
import pandas as pd

from sklearn.metrics import f1_score

In [3]:
from operator import itemgetter
import pickle
import datetime
import os

In [4]:
THEORY_ROOT_DIR='/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318'

## Import the data

We've got the DataFrames containing the data in the file `bea_2way_data.pickle`. Load that in:

In [5]:
with open("bea_2way_data.pickle", "br") as fIn:
    d = pickle.load(fIn)

all_questions_df = d["questions"]
all_responses_df = d["responses"]
all_text_df = d["text"]

In [6]:
all_questions_df.head()

,original_question_id,question_id,question,correct,incorrect_1,incorrect_2,correct_id,incorrect_1_id,incorrect_2_id
0,fcf5ff56-5e98-4eb7-8df3-afb0544d9739,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,"Die SuS erklären, dass durch die unterschiedli...","Die SuS erklären nicht, dass dadurch die Mögli...","Die SuS erklären, dass durch die unterschiedli...",c_00,i_00,j_00
1,c51b89a6-0219-4eee-bb89-b2b5168998f5,q_01,Begründe deine Auswahl.,Die Schüler:innen stellen einen Zusammenhang z...,Die Schüler:innen stellen keinen Zusammenhang ...,Die Schüler:innen stellen einen Zusammenhang z...,c_01,i_01,j_01
2,379ba896-bb8f-440d-9d32-5dc9ca0297fe,q_02,Formuliere selbst eine Fragestellung.,Die SuS beschreiben die durchschnittliche Gesc...,Die SuS beschreiben weder die durchschnittlich...,Die SuS beschreiben entweder die durchschnittl...,c_02,i_02,j_02
3,cb99dfb3-2788-4a10-b934-7ea8276b2b44,q_03,Beschreibe auf Basis Deines Vorwissens die Erk...,"Die Schüler:innen erläutern den Vorteil, dass ...",Die Schüler:innen erläutern den erweiterten Bl...,"Die Schüler:innen erläuten den Vorteil, dass d...",c_03,i_03,j_03
4,b85b1a95-35ba-473e-a164-4602a4a13a2f,q_04,In dem Video siehst du die abstrakte Funktions...,Die SuS beschreiben die Funktionsweise eines D...,Die SuS beschreiben die Funktionsweise nicht k...,"Die SuS beschreiben nur einen Teil, entweder d...",c_04,i_04,j_04

In [7]:
all_responses_df.head()

,original_response_id,response_id,question_id,response,score,partition
0,e78122dd-9f3c-456e-a546-fc905b023807,r_0111,q_00,Im Winter ist weniger Strahlung weil die Sonne...,incorrect,train
1,4cf98df5-8d79-4144-aeea-37df3bec5de5,r_0115,q_00,Es kann im Süden und Sommer mehr elektrische E...,incorrect,train
2,6550b62c-cc65-458d-a609-a7a38c45cbca,r_0129,q_00,da im sommer mehr die somme scheint gibt es au...,incorrect,train
3,e4d9c6e1-ed55-468a-9101-89218a989852,r_0178,q_00,im Sommer gewinnt man die meiste Energie wobei...,incorrect,train
4,7d3e3263-668f-4283-ab26-edd6d4c43be1,r_0292,q_00,Im Winter ist am wenigsten Energie da im Winte...,incorrect,train

In [8]:
all_text_df.head()

,id,text,i,word_text,lemma
0,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,0,Erläutere,erläuter
1,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,1,die,der
2,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,2,Auswirkungen,auswirkung
3,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,3,der,der
4,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,4,jahreszeitabhängigen,jahreszeitabhängig

## Run on a single example case as a tester

I realised that my code doesn't always assign the same Amati codes to the original IDs, so start by selecting a test case from the original question code:

Let's try working through the functions in `amati_bea.py`.

In [9]:
TEST_QUESTION_ID = "fcf5ff56-5e98-4eb7-8df3-afb0544d9739"
TEST_QUESTION_ID

'fcf5ff56-5e98-4eb7-8df3-afb0544d9739'

We now pull out the Series containing this ID as the one to work with:

In [10]:
question_ss = all_questions_df.set_index("original_question_id").T[TEST_QUESTION_ID]

question_ss

question_id                                                    q_00
question          Erläutere die Auswirkungen der jahreszeitabhän...
correct           Die SuS erklären, dass durch die unterschiedli...
incorrect_1       Die SuS erklären nicht, dass dadurch die Mögli...
incorrect_2       Die SuS erklären, dass durch die unterschiedli...
correct_id                                                     c_00
incorrect_1_id                                                 i_00
incorrect_2_id                                                 j_00
Name: fcf5ff56-5e98-4eb7-8df3-afb0544d9739, dtype: object

For the responses, want just the training cases, not the trial cases.

In [11]:
responses_df = all_responses_df.query("`question_id`==@question_ss['question_id']").query(
    "`partition`=='train'"
)
responses_df

,original_response_id,response_id,question_id,response,score,partition
0,e78122dd-9f3c-456e-a546-fc905b023807,r_0111,q_00,Im Winter ist weniger Strahlung weil die Sonne...,incorrect,train
1,4cf98df5-8d79-4144-aeea-37df3bec5de5,r_0115,q_00,Es kann im Süden und Sommer mehr elektrische E...,incorrect,train
2,6550b62c-cc65-458d-a609-a7a38c45cbca,r_0129,q_00,da im sommer mehr die somme scheint gibt es au...,incorrect,train
3,e4d9c6e1-ed55-468a-9101-89218a989852,r_0178,q_00,im Sommer gewinnt man die meiste Energie wobei...,incorrect,train
4,7d3e3263-668f-4283-ab26-edd6d4c43be1,r_0292,q_00,Im Winter ist am wenigsten Energie da im Winte...,incorrect,train
...,...,...,...,...,...,...
92,8ceef6e1-5902-485c-8b2d-23204dcc3f4d,r_7672,q_00,"Im Winter bin ich mir sicher , dass die Strahl...",incorrect,train
93,7df30d21-fc6c-4577-a14d-e621068f6847,r_7675,q_00,"Im Sommer scheint die Sonne sehr viel , aber i...",correct,train
94,14645435-9103-45a8-89b2-60e2ebf4502e,r_7698,q_00,Spannung und Stromstärke in Abhängigkeit der W...,incorrect,train
95,9410add7-f86b-4d73-8334-785dbd5cf22b,r_7739,q_00,Man kann erkennen das man im Winter nicht die ...,incorrect,train
96,58f4d352-4fee-4d9c-88d0-c057c111799c,r_7775,q_00,Ö\n,incorrect,train

In [12]:
texts_used = [
    question_ss["question_id"],
    question_ss["correct_id"],
    question_ss["incorrect_1_id"],
    question_ss["incorrect_2_id"],
] + list(responses_df["response_id"])

text_df = all_text_df.query("`id`.isin(@texts_used)")[["id", "i", "lemma"]]
text_df

           id   i               lemma
0        q_00   0            erläuter
1        q_00   1                 der
2        q_00   2          auswirkung
3        q_00   3                 der
4        q_00   4  jahreszeitabhängig
...       ...  ..                 ...
10524  r_7739  30               immer
10525  r_7739  31                mehr
10526  r_7739  32               strom
10527  r_7739  33           benötigen
10529  r_7775   0                   ö

[3134 rows x 3 columns]

OK, that should cover what we want.

----------------

## Generate the positive and negative cases

OK, now to start with the `amati_bea` functions.

Let's start off by generating positive and negative cases.

In [13]:
accuracy_classes = set(responses_df["score"])
accuracy_classes

{'correct', 'incorrect'}

In [14]:
responses_df

,original_response_id,response_id,question_id,response,score,partition
0,e78122dd-9f3c-456e-a546-fc905b023807,r_0111,q_00,Im Winter ist weniger Strahlung weil die Sonne...,incorrect,train
1,4cf98df5-8d79-4144-aeea-37df3bec5de5,r_0115,q_00,Es kann im Süden und Sommer mehr elektrische E...,incorrect,train
2,6550b62c-cc65-458d-a609-a7a38c45cbca,r_0129,q_00,da im sommer mehr die somme scheint gibt es au...,incorrect,train
3,e4d9c6e1-ed55-468a-9101-89218a989852,r_0178,q_00,im Sommer gewinnt man die meiste Energie wobei...,incorrect,train
4,7d3e3263-668f-4283-ab26-edd6d4c43be1,r_0292,q_00,Im Winter ist am wenigsten Energie da im Winte...,incorrect,train
...,...,...,...,...,...,...
92,8ceef6e1-5902-485c-8b2d-23204dcc3f4d,r_7672,q_00,"Im Winter bin ich mir sicher , dass die Strahl...",incorrect,train
93,7df30d21-fc6c-4577-a14d-e621068f6847,r_7675,q_00,"Im Sommer scheint die Sonne sehr viel , aber i...",correct,train
94,14645435-9103-45a8-89b2-60e2ebf4502e,r_7698,q_00,Spannung und Stromstärke in Abhängigkeit der W...,incorrect,train
95,9410add7-f86b-4d73-8334-785dbd5cf22b,r_7739,q_00,Man kann erkennen das man im Winter nicht die ...,incorrect,train
96,58f4d352-4fee-4d9c-88d0-c057c111799c,r_7775,q_00,Ö\n,incorrect,train

In [15]:
pos_cases_df = responses_df[["response_id", "question_id", "score"]].sort_values(
    "response_id", ignore_index=True
)

pos_cases_df.sort_values("response_id", ignore_index=True)

   response_id question_id      score
0       r_0111        q_00  incorrect
1       r_0115        q_00  incorrect
2       r_0129        q_00  incorrect
3       r_0178        q_00  incorrect
4       r_0292        q_00  incorrect
..         ...         ...        ...
92      r_7672        q_00  incorrect
93      r_7675        q_00    correct
94      r_7698        q_00  incorrect
95      r_7739        q_00  incorrect
96      r_7775        q_00  incorrect

[97 rows x 3 columns]

In [16]:
neg_cases_df = (
    pd.concat([responses_df.assign(classes=c) for c in accuracy_classes])
    .query("`score`!=`classes`")
    .drop(["score", "partition"], axis="columns")
    .rename({"classes": "score"}, axis="columns")[
        ["response_id", "question_id", "score"]
    ]
    .sort_values("response_id", ignore_index=True)
)


neg_cases_df

   response_id question_id      score
0       r_0111        q_00    correct
1       r_0115        q_00    correct
2       r_0129        q_00    correct
3       r_0178        q_00    correct
4       r_0292        q_00    correct
..         ...         ...        ...
92      r_7672        q_00    correct
93      r_7675        q_00  incorrect
94      r_7698        q_00    correct
95      r_7739        q_00    correct
96      r_7775        q_00    correct

[97 rows x 3 columns]

------------------------

I think what I want is to be able to send those structures to `amati_bea.py` and see how it goes from there.

Check that the function `build_amati_training_file` works correctly:

In [17]:
# default file name and stopwords

amati.build_amati_training_file(
    positive_examples_df=pos_cases_df,
    negative_examples_df=neg_cases_df,
    responses_df=responses_df,
    text_df=text_df,
    rulesfile="clingo_program_files/bea_rules.amati",
    # filename="amati_induction.lp",
    question_ss=question_ss,
    stopwords=True,
)

True

OK, that seems OK. Now, what about an actual induction run? Check the behaviour of `induce_once` first:

In [18]:
x = amati.induce_once(
    positive_examples_df=pos_cases_df,
    negative_examples_df=neg_cases_df,
    responses_df=responses_df,
    text_df=text_df,
    question_ss=question_ss,
    rulesfile="clingo_program_files/bea_rules.amati",
    time_limit=10,
    min_precision=0.8,
    min_coverage=2,
)

x

{'result': 'SATISFIABLE',
 'selected_rule': ('rule1', 'selected_rule(rule1)'),
 'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
 'parameters': [(1, '"es"', 'parameter(1,"es")'),
  (2, '"sommer"', 'parameter(2,"sommer")')],
 'positive_covered': ['r_0115',
  'r_0129',
  'r_0178',
  'r_0292',
  'r_0792',
  'r_1140',
  'r_1210',
  'r_2196',
  'r_2876',
  'r_3295',
  'r_3882',
  'r_4025',
  'r_4218',
  'r_5282',
  'r_5809',
  'r_5846',
  'r_5895',
  'r_6185',
  'r_7672'],
 'negative_covered': ['r_1461', 'r_2270', 'r_7675'],
 'evaluations': {'precision': 86,
  'compression': 16,
  'coverage': 16,
  'accuracy': 86},
 'positive_df':    response_id question_id      score  covered
 0       r_0111        q_00  incorrect    False
 1       r_0115        q_00  incorrect     True
 2       r_0129        q_00  incorrect     True
 3       r_0178        q_00  incorrect     True
 4       r_0292        q_00  incorrect     True
 ..         ...         ...        ...      ...
 92      r_7672        q_00  incorrect     True
 93      r_7675        q_00    correct    False
 94      r_7698        q_00  incorrect    False
 95      r_7739        q_00  incorrect    False
 96      r_7775        q_00  incorrect    False

 [97 rows x 4 columns],
 'negative_df':    response_id question_id      score  covered
 0       r_0111        q_00    correct    False
 1       r_0115        q_00    correct    False
 2       r_0129        q_00    correct    False
 3       r_0178        q_00    correct    False
 4       r_0292        q_00    correct    False
 ..         ...         ...        ...      ...
 92      r_7672        q_00    correct    False
 93      r_7675        q_00  incorrect     True
 94      r_7698        q_00    correct    False
 95      r_7739        q_00    correct    False
 96      r_7775        q_00    correct    False

 [97 rows x 4 columns]}

OK, and then do a complete run:

In [19]:
x = amati.induce_theory(
    positive_examples_df=pos_cases_df,
    negative_examples_df=neg_cases_df,
    responses_df=responses_df,
    text_df=text_df,
    question_ss=question_ss,
    rulesfile="clingo_program_files/bea_rules.amati",
    time_limit=10,
    min_precision=0.8,
    min_coverage=2,
)

97 84 75 69 64 54 49 45 42 39 36 34 32 28 26 24 22 20 18 16

In [20]:
x

[{'result': 'SATISFIABLE',
  'selected_rule': ('rule1', 'selected_rule(rule1)'),
  'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
  'parameters': [(1, '"sonne"', 'parameter(1,"sonne")'),
   (2, '"seehr"', 'parameter(2,"seehr")')],
  'positive_covered': ['r_0111',
   'r_0792',
   'r_0958',
   'r_1903',
   'r_1942',
   'r_2238',
   'r_2863',
   'r_4025',
   'r_4179',
   'r_4218',
   'r_4655',
   'r_5809',
   'r_6546'],
  'negative_covered': ['r_2270', 'r_5376', 'r_7675'],
  'evaluations': {'precision': 81,
   'compression': 10,
   'coverage': 10,
   'accuracy': 81},
  'positive_df':    response_id question_id      score  covered
  0       r_0111        q_00  incorrect     True
  1       r_0115        q_00  incorrect    False
  2       r_0129        q_00  incorrect    False
  3       r_0178        q_00  incorrect    False
  4       r_0292        q_00  incorrect    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00  incorrect    False
  93      r_7675        q_00    correct    False
  94      r_7698        q_00  incorrect    False
  95      r_7739        q_00  incorrect    False
  96      r_7775        q_00  incorrect    False

  [97 rows x 4 columns],
  'negative_df':    response_id question_id      score  covered
  0       r_0111        q_00    correct    False
  1       r_0115        q_00    correct    False
  2       r_0129        q_00    correct    False
  3       r_0178        q_00    correct    False
  4       r_0292        q_00    correct    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00    correct    False
  93      r_7675        q_00  incorrect     True
  94      r_7698        q_00    correct    False
  95      r_7739        q_00    correct    False
  96      r_7775        q_00    correct    False

  [97 rows x 4 columns]},
 {'result': 'SATISFIABLE',
  'selected_rule': ('rule1', 'selected_rule(rule1)'),
  'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
  'parameters': [(1, '"produzieren"', 'parameter(1,"produzieren")'),
   (2, '"winter"', 'parameter(2,"winter")')],
  'positive_covered': ['r_0641',
   'r_2456',
   'r_3882',
   'r_4209',
   'r_5357',
   'r_5490',
   'r_5846',
   'r_5895',
   'r_7212'],
  'negative_covered': [],
  'evaluations': {'precision': 100,
   'compression': 9,
   'coverage': 9,
   'accuracy': 100},
  'positive_df':    response_id question_id      score  covered
  1       r_0115        q_00  incorrect    False
  2       r_0129        q_00  incorrect    False
  3       r_0178        q_00  incorrect    False
  4       r_0292        q_00  incorrect    False
  5       r_0342        q_00  incorrect    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00  incorrect    False
  93      r_7675        q_00    correct    False
  94      r_7698        q_00  incorrect    False
  95      r_7739        q_00  incorrect    False
  96      r_7775        q_00  incorrect    False

  [84 rows x 4 columns],
  'negative_df':    response_id question_id      score  covered
  0       r_0111        q_00    correct    False
  1       r_0115        q_00    correct    False
  2       r_0129        q_00    correct    False
  3       r_0178        q_00    correct    False
  4       r_0292        q_00    correct    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00    correct    False
  93      r_7675        q_00  incorrect    False
  94      r_7698        q_00    correct    False
  95      r_7739        q_00    correct    False
  96      r_7775        q_00    correct    False

  [97 rows x 4 columns]},
 {'result': 'SATISFIABLE',
  'selected_rule': ('rule1', 'selected_rule(rule1)'),
  'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
  'parameters': [(1, '"norden"', 'parameter(1,"norden")'),
   (2, '"bzw."', 'parameter(2,"bzw.")')],
  'positive_covered': ['r_0115',
   'r_0917',
   'r_1140',
   'r_3140',
   'r_6734',
   'r_7379'],
  'negative_covered': [],
  'evaluations': {'precision': 100,
   'compression': 6,
   'coverage': 6,
   'accuracy': 100},
  'positive_df':    response_id question_id      score  covered
  1       r_0115        q_00  incorrect     True
  2       r_0129        q_00  incorrect    False
  3       r_0178        q_00  incorrect    False
  4       r_0292        q_00  incorrect    False
  5       r_0342        q_00  incorrect    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00  incorrect    False
  93      r_7675        q_00    correct    False
  94      r_7698        q_00  incorrect    False
  95      r_7739        q_00  incorrect    False
  96      r_7775        q_00  incorrect    False

  [75 rows x 4 columns],
  'negative_df':    response_id question_id      score  covered
  0       r_0111        q_00    correct    False
  1       r_0115        q_00    correct    False
  2       r_0129        q_00    correct    False
  3       r_0178        q_00    correct    False
  4       r_0292        q_00    correct    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00    correct    False
  93      r_7675        q_00  incorrect    False
  94      r_7698        q_00    correct    False
  95      r_7739        q_00    correct    False
  96      r_7775        q_00    correct    False

  [97 rows x 4 columns]},
 {'result': 'SATISFIABLE',
  'selected_rule': ('rule1', 'selected_rule(rule1)'),
  'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
  'parameters': [(1, '"0,01"', 'parameter(1,"0,01")'),
   (2, '"0,0097"', 'parameter(2,"0,0097")')],
  'positive_covered': ['r_0342', 'r_2187', 'r_6991', 'r_7306', 'r_7698'],
  'negative_covered': [],
  'evaluations': {'precision': 100,
   'compression': 5,
   'coverage': 5,
   'accuracy': 100},
  'positive_df':    response_id question_id      score  covered
  2       r_0129        q_00  incorrect    False
  3       r_0178        q_00  incorrect    False
  4       r_0292        q_00  incorrect    False
  5       r_0342        q_00  incorrect     True
  6       r_0470        q_00  incorrect    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00  incorrect    False
  93      r_7675        q_00    correct    False
  94      r_7698        q_00  incorrect     True
  95      r_7739        q_00  incorrect    False
  96      r_7775        q_00  incorrect    False

  [69 rows x 4 columns],
  'negative_df':    response_id question_id      score  covered
  0       r_0111        q_00    correct    False
  1       r_0115        q_00    correct    False
  2       r_0129        q_00    correct    False
  3       r_0178        q_00    correct    False
  4       r_0292        q_00    correct    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00    correct    False
  93      r_7675        q_00  incorrect    False
  94      r_7698        q_00    correct    False
  95      r_7739        q_00    correct    False
  96      r_7775        q_00    correct    False

  [97 rows x 4 columns]},
 {'result': 'OPTIMUM FOUND',
  'selected_rule': ('rule2', 'selected_rule(rule2)'),
  'predicted_grade': ('correct', 'predicted_grade(correct)'),
  'parameters': [(1,
    '"strahlungsenergie"',
    'parameter(1,"strahlungsenergie")'),
   (2, '"energie"', 'parameter(2,"energie")')],
  'positive_covered': ['r_0918',
   'r_1262',
   'r_1745',
   'r_2308',
   'r_2813',
   'r_3208',
   'r_4563',
   'r_5728',
   'r_5952',
   'r_6685'],
  'negative_covered': ['r_0637', 'r_1532'],
  'evaluations': {'precision': 83,
   'compression': 7,
   'coverage': 8,
   'accuracy': 83},
  'positive_df':    response_id question_id      score  covered
  2       r_0129        q_00  incorrect    False
  3       r_0178        q_00  incorrect    False
  4       r_0292        q_00  incorrect    False
  6       r_0470        q_00  incorrect    False
  7       r_0637        q_00  incorrect    False
  ..         ...         ...        ...      ...
  91      r_7434        q_00  incorrect    False
  92      r_7672        q_00  incorrect    False
  93      r_7675        q_00    correct    False
  95      r_7739        q_00  incorrect    False
  96      r_7775        q_00  incorrect    False

  [64 rows x 4 columns],
  'negative_df':    response_id question_id      score  covered
  0       r_0111        q_00    correct    False
  1       r_0115        q_00    correct    False
  2       r_0129        q_00    correct    False
  3       r_0178        q_00    correct    False
  4       r_0292        q_00    correct    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00    correct    False
  93      r_7675        q_00  incorrect    False
  94      r_7698        q_00    correct    False
  95      r_7739        q_00    correct    False
  96      r_7775        q_00    correct    False

  [97 rows x 4 columns]},
 {'result': 'OPTIMUM FOUND',
  'selected_rule': ('rule1', 'selected_rule(rule1)'),
  'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
  'parameters': [(1, '"geben"', 'parameter(1,"geben")'),
   (2, '"energie"', 'parameter(2,"energie")')],
  'positive_covered': ['r_0129', 'r_0178', 'r_0292', 'r_1210', 'r_2196'],
  'negative_covered': [],
  'evaluations': {'precision': 100,
   'compression': 5,
   'coverage': 5,
   'accuracy': 100},
  'positive_df':    response_id question_id      score  covered
  2       r_0129        q_00  incorrect     True
  3       r_0178        q_00  incorrect     True
  4       r_0292        q_00  incorrect     True
  6       r_0470        q_00  incorrect    False
  7       r_0637        q_00  incorrect    False
  9       r_0680        q_00  incorrect    False
  11      r_0869        q_00  incorrect    False
  12      r_0895        q_00  incorrect    False
  16      r_1081        q_00    correct    False
  18      r_1210        q_00  incorrect     True
  20      r_1461        q_00    correct    False
  21      r_1532        q_00  incorrect    False
  22      r_1537        q_00  incorrect    False
  23      r_1628        q_00  incorrect    False
  25      r_1835        q_00  incorrect    False
  29      r_2196        q_00  incorrect     True
  31      r_2270        q_00    correct    False
  33      r_2429        q_00  incorrect    False
  35      r_2504        q_00  incorrect    False
  36      r_2548        q_00  incorrect    False
  37      r_2728        q_00  incorrect    False
  40      r_2876        q_00  incorrect    False
  41      r_3087        q_00  incorrect    False
  44      r_3295        q_00  incorrect    False
  45      r_3501        q_00  incorrect    False
  46      r_3511        q_00    correct    False
  47      r_3528        q_00    correct    False
  48      r_3837        q_00    correct    False
  49      r_3843        q_00  incorrect    False
  52      r_4145        q_00    correct    False
  55      r_4212        q_00    correct    False
  59      r_4907        q_00  incorrect    False
  60      r_5064        q_00    correct    False
  61      r_5192        q_00  incorrect    False
  62      r_5282        q_00  incorrect    False
  63      r_5323        q_00  incorrect    False
  65      r_5376        q_00    correct    False
  66      r_5437        q_00  incorrect    False
  68      r_5665        q_00    correct    False
  71      r_5815        q_00    correct    False
  72      r_5827        q_00  incorrect    False
  76      r_5965        q_00  incorrect    False
  77      r_6076        q_00  incorrect    False
  78      r_6130        q_00    correct    False
  79      r_6185        q_00  incorrect    False
  81      r_6576        q_00    correct    False
  82      r_6650        q_00  incorrect    False
  85      r_6774        q_00  incorrect    False
  86      r_6965        q_00  incorrect    False
  91      r_7434        q_00  incorrect    False
  92      r_7672        q_00  incorrect    False
  93      r_7675        q_00    correct    False
  95      r_7739        q_00  incorrect    False
  96      r_7775        q_00  incorrect    False,
  'negative_df':    response_id question_id      score  covered
  0       r_0111        q_00    correct    False
  1       r_0115        q_00    correct    False
  2       r_0129        q_00    correct    False
  3       r_0178        q_00    correct    False
  4       r_0292        q_00    correct    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00    correct    False
  93      r_7675        q_00  incorrect    False
  94      r_7698        q_00    correct    False
  95      r_7739        q_00    correct    False
  96      r_7775        q_00    correct    False

  [97 rows x 4 columns]},
 {'result': 'OPTIMUM FOUND',
  'selected_rule': ('rule1', 'selected_rule(rule1)'),
  'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
  'parameters': [(1, '"solarenergie"', 'parameter(1,"solarenergie")')],
  'positive_covered': ['r_1537', 'r_1835', 'r_4907', 'r_5965'],
  'negative_covered': [],
  'evaluations': {'precision': 100,
   'compression': 4,
   'coverage': 4,
   'accuracy': 100},
  'positive_df':    response_id question_id      score  covered
  6       r_0470        q_00  incorrect    False
  7       r_0637        q_00  incorrect    False
  9       r_0680        q_00  incorrect    False
  11      r_0869        q_00  incorrect    False
  12      r_0895        q_00  incorrect    False
  16      r_1081        q_00    correct    False
  20      r_1461        q_00    correct    False
  21      r_1532        q_00  incorrect    False
  22      r_1537        q_00  incorrect     True
  23      r_1628        q_00  incorrect    False
  25      r_1835        q_00  incorrect     True
  31      r_2270        q_00    correct    False
  33      r_2429        q_00  incorrect    False
  35      r_2504        q_00  incorrect    False
  36      r_2548        q_00  incorrect    False
  37      r_2728        q_00  incorrect    False
  40      r_2876        q_00  incorrect    False
  41      r_3087        q_00  incorrect    False
  44      r_3295        q_00  incorrect    False
  45      r_3501        q_00  incorrect    False
  46      r_3511        q_00    correct    False
  47      r_3528        q_00    correct    False
  48      r_3837        q_00    correct    False
  49      r_3843        q_00  incorrect    False
  52      r_4145        q_00    correct    False
  55      r_4212        q_00    correct    False
  59      r_4907        q_00  incorrect     True
  60      r_5064        q_00    correct    False
  61      r_5192        q_00  incorrect    False
  62      r_5282        q_00  incorrect    False
  63      r_5323        q_00  incorrect    False
  65      r_5376        q_00    correct    False
  66      r_5437        q_00  incorrect    False
  68      r_5665        q_00    correct    False
  71      r_5815        q_00    correct    False
  72      r_5827        q_00  incorrect    False
  76      r_5965        q_00  incorrect     True
  77      r_6076        q_00  incorrect    False
  78      r_6130        q_00    correct    False
  79      r_6185        q_00  incorrect    False
  81      r_6576        q_00    correct    False
  82      r_6650        q_00  incorrect    False
  85      r_6774        q_00  incorrect    False
  86      r_6965        q_00  incorrect    False
  91      r_7434        q_00  incorrect    False
  92      r_7672        q_00  incorrect    False
  93      r_7675        q_00    correct    False
  95      r_7739        q_00  incorrect    False
  96      r_7775        q_00  incorrect    False,
  'negative_df':    response_id question_id      score  covered
  0       r_0111        q_00    correct    False
  1       r_0115        q_00    correct    False
  2       r_0129        q_00    correct    False
  3       r_0178        q_00    correct    False
  4       r_0292        q_00    correct    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00    correct    False
  93      r_7675        q_00  incorrect    False
  94      r_7698        q_00    correct    False
  95      r_7739        q_00    correct    False
  96      r_7775        q_00    correct    False

  [97 rows x 4 columns]},
 {'result': 'OPTIMUM FOUND',
  'selected_rule': ('rule1', 'selected_rule(rule1)'),
  'predicted_grade': ('correct', 'predicted_grade(correct)'),
  'parameters': [(1, '"sommermonat"', 'parameter(1,"sommermonat")'),
   (2, '"efektiv"', 'parameter(2,"efektiv")')],
  'positive_covered': ['r_3528', 'r_5376', 'r_5815'],
  'negative_covered': [],
  'evaluations': {'precision': 100,
   'compression': 3,
   'coverage': 3,
   'accuracy': 100},
  'positive_df':    response_id question_id      score  covered
  6       r_0470        q_00  incorrect    False
  7       r_0637        q_00  incorrect    False
  9       r_0680        q_00  incorrect    False
  11      r_0869        q_00  incorrect    False
  12      r_0895        q_00  incorrect    False
  16      r_1081        q_00    correct    False
  20      r_1461        q_00    correct    False
  21      r_1532        q_00  incorrect    False
  23      r_1628        q_00  incorrect    False
  31      r_2270        q_00    correct    False
  33      r_2429        q_00  incorrect    False
  35      r_2504        q_00  incorrect    False
  36      r_2548        q_00  incorrect    False
  37      r_2728        q_00  incorrect    False
  40      r_2876        q_00  incorrect    False
  41      r_3087        q_00  incorrect    False
  44      r_3295        q_00  incorrect    False
  45      r_3501        q_00  incorrect    False
  46      r_3511        q_00    correct    False
  47      r_3528        q_00    correct     True
  48      r_3837        q_00    correct    False
  49      r_3843        q_00  incorrect    False
  52      r_4145        q_00    correct    False
  55      r_4212        q_00    correct    False
  60      r_5064        q_00    correct    False
  61      r_5192        q_00  incorrect    False
  62      r_5282        q_00  incorrect    False
  63      r_5323        q_00  incorrect    False
  65      r_5376        q_00    correct     True
  66      r_5437        q_00  incorrect    False
  68      r_5665        q_00    correct    False
  71      r_5815        q_00    correct     True
  72      r_5827        q_00  incorrect    False
  77      r_6076        q_00  incorrect    False
  78      r_6130        q_00    correct    False
  79      r_6185        q_00  incorrect    False
  81      r_6576        q_00    correct    False
  82      r_6650        q_00  incorrect    False
  85      r_6774        q_00  incorrect    False
  86      r_6965        q_00  incorrect    False
  91      r_7434        q_00  incorrect    False
  92      r_7672        q_00  incorrect    False
  93      r_7675        q_00    correct    False
  95      r_7739        q_00  incorrect    False
  96      r_7775        q_00  incorrect    False,
  'negative_df':    response_id question_id      score  covered
  0       r_0111        q_00    correct    False
  1       r_0115        q_00    correct    False
  2       r_0129        q_00    correct    False
  3       r_0178        q_00    correct    False
  4       r_0292        q_00    correct    False
  ..         ...         ...        ...      ...
  92      r_7672        q_00    correct    False
  93      r_7675        q_00  incorrect    False
  94      r_7698        q_00    correct    False
  95      r_7739        q_00    correct    False
  96      r_7775        q_00    correct    False

  [97 rows x 4 columns]},
 {'result': 'OPTIMUM FOUND',
  'selected_rule': ('rule1', 'selected_rule(rule1)'),
  'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
  'parameters': [(1, '"anfang"', 'parameter(1,"anfang")'),
   (2, '"sommer"', 'parameter(2,"sommer")')],
  'positive_covered': ['r_2876', 'r_5282', 'r_5323'],
  'negative_covered': [],
  'evaluations': {'precision': 100,
   'compression': 3,
   'coverage': 3,
   'accuracy': 100},

In [21]:
x[-1]

{'result': 'UNSATISFIABLE',
 'selected_rule': None,
 'predicted_grade': None,
 'parameters': None,
 'positive_covered': [],
 'negative_covered': [],
 'evaluation': None,
 'positive_df':    response_id question_id      score  covered
 11      r_0869        q_00  incorrect    False
 12      r_0895        q_00  incorrect    False
 16      r_1081        q_00    correct    False
 20      r_1461        q_00    correct    False
 23      r_1628        q_00  incorrect    False
 35      r_2504        q_00  incorrect    False
 37      r_2728        q_00  incorrect    False
 45      r_3501        q_00  incorrect    False
 49      r_3843        q_00  incorrect    False
 60      r_5064        q_00    correct    False
 68      r_5665        q_00    correct    False
 78      r_6130        q_00    correct    False
 79      r_6185        q_00  incorrect    False
 81      r_6576        q_00    correct    False
 85      r_6774        q_00  incorrect    False
 95      r_7739        q_00  incorrect    False,
 'negative_df':    response_id question_id      score  covered
 0       r_0111        q_00    correct    False
 1       r_0115        q_00    correct    False
 2       r_0129        q_00    correct    False
 3       r_0178        q_00    correct    False
 4       r_0292        q_00    correct    False
 ..         ...         ...        ...      ...
 92      r_7672        q_00    correct    False
 93      r_7675        q_00  incorrect    False
 94      r_7698        q_00    correct    False
 95      r_7739        q_00    correct    False
 96      r_7775        q_00    correct    False

 [97 rows x 4 columns]}

Actually, let's just call that the theory. Should be able to pickle it...

with open(f"theory_{question_ss['original_question_id']}.pickle", "wb") as fOut:
    pickle.dump(x, fOut)

In [22]:
def induce_theory(
    original_question_id,
    data_file="bea_2way_data.pickle",
    rulesfile="clingo_program_files/bea_rules.amati",
    time_limit=120,
    min_precision=0.8,
    min_coverage=2,
):
    """question_id is the original version, not the"
    shortened version"""

    with open("bea_2way_data.pickle", "br") as fIn:
        d = pickle.load(fIn)
        all_questions_df = d["questions"]
        all_responses_df = d["responses"]
        all_text_df = d["text"]

    question_ss = all_questions_df.set_index("original_question_id").T[
        original_question_id
    ]
    question_id = question_ss["question_id"]

    # To induce the theory, just want the training cases

    responses_df = all_responses_df.query("`question_id`==@question_id").query(
        "`partition`=='train'"
    )

    texts_used = [
        question_ss["question_id"],
        question_ss["correct_id"],
        question_ss["incorrect_1_id"],
        question_ss["incorrect_2_id"],
    ] + list(responses_df["response_id"])

    text_df = all_text_df.query("`id`.isin(@texts_used)")[["id", "i", "lemma"]]

    # Next, need the positive and negative cases

    accuracy_classes = set(responses_df["score"])

    pos_cases_df = responses_df[["response_id", "question_id", "score"]].sort_values(
        "response_id", ignore_index=True
    )

    neg_cases_df = (
        pd.concat([responses_df.assign(classes=c) for c in accuracy_classes])
        .query("`score`!=`classes`")
        .drop(["score", "partition"], axis="columns")
        .rename({"classes": "score"}, axis="columns")[
            ["response_id", "question_id", "score"]
        ]
        .sort_values("response_id", ignore_index=True)
    )

    output = {
        "theory": amati.induce_theory(
            positive_examples_df=pos_cases_df,
            negative_examples_df=neg_cases_df,
            responses_df=responses_df,
            text_df=text_df,
            question_ss=question_ss,
            rulesfile=rulesfile,
            time_limit=time_limit,
            min_precision=min_precision,
            min_coverage=min_coverage,
        )
    }

    output["original_question_id"] = original_question_id
    output["question_id"] = question_id

    output["all_questions_df"] = all_questions_df
    output["all_responses_df"] = all_responses_df
    output["all_text_df"] = all_text_df

    with open(rulesfile) as fIn:
        output["rules"] = fIn.read()

    return output

## Apply to the complete set

We should now be able to apply to the complete set of questions.

In [23]:
with open("bea_2way_data.pickle", "br") as fIn:
    p = pickle.load(fIn)

for q_id in set(p["questions"]["original_question_id"]):
    print(q_id)
    d = datetime.datetime.now()
    theory_file_name = os.path.join(THEORY_ROOT_DIR, f"theory_{q_id}_{d.date()}_{d.time()}.pickle"
    )
    with open(theory_file_name, "wb") as fOut:
        pickle.dump(induce_theory(q_id), fOut)

64636904-aab6-4e10-a4dc-39638117731a
216 24 19 17 15 8e686080-6db7-473b-baa0-6f17412fae5c
157 116 93 74 64 55 47 41 35 31 29 27 25 23 21 19 dee4136e-e922-4b83-8033-24350ea1610c
124 50 40 36 33 31 28 26 24 22 20 dddf3a9d-2f40-402c-b650-3db1b27128ca
74 63 55 48 44 41 39 37 35 33 31 29 26 24 22 b5fb6924-1da3-45b1-a386-68e95d80b057
196 93 79 69 65 60 54 50 47 45 43 41 39 36 34 31 29 27 25 23 33c179c8-ee50-4a7b-b139-8b2984356400
45 29 25 21 18 16 14 278f349f-1552-41c4-bec2-1de41838f229
145 57 39 31 26 23 21 19 16 14 12 8a35dfaf-e9d0-466d-98b8-1e1b132bb450
187 161 139 127 118 112 107 103 100 97 94 90 86 84 81 79 76 72 70 68 66 64 62 60 58 56 54 52 50 48 46 44 42 40 38 d9e775ff-b54e-4558-86eb-0251737ecdf1
27 14 7 5 3 d14cc74c-805a-45f7-9ad3-2e9f19395ca0
73 30 23 20 17 15 12 10 8 0f036c26-4a47-48ba-b913-f27487286ac7
64 55 49 45 41 38 34 32 30 8144573c-97d6-484a-b68b-c16b7602fa7b
98 81 68 61 55 51 46 42 39 37 35 32 30 26 379ba896-bb8f-440d-9d32-5dc9ca0297fe
180 23 17 15 13 11 48071573-9e44-4ae9-b08c-2b19b6ee58d6
40 13 6 e6f0fdac-98cd-4ad5-a700-cb612f4ec827
74 54 47 42 39 36 34 32 30 28 24 22 20 cb99dfb3-2788-4a10-b934-7ea8276b2b44
139 123 108 100 94 89 84 79 75 73 70 68 66 64 62 60 58 56 54 51 49 47 45 43 41 39 b3978794-9681-49bd-bc9b-d05bf8d226d8
141 15 8 6 4 82aacab8-0c7f-4936-b93f-62c53670b5c3
158 107 96 86 77 71 66 62 59 56 54 52 50 48 46 44 42 40 38 36 bbb0e987-436a-46f3-b16d-34fd708f8236
21 13 11 5f7bd982-606b-45e4-bf39-89db6714a621
59 25 13 11 9 7 11be53c7-c020-445b-b3a4-409d4ba16347
93 86 81 76 73 71 69 67 65 63 61 59 57 55 b1d2b0f3-f2d0-4be0-850f-1b7810acd965
42 30 24 21 18 16 14 12 1f2f0773-54bb-4b72-963e-c3c946a1f53f
126 119 111 107 103 100 97 94 90 87 84 81 77 75 73 71 69 67 65 63 61 59 57 55 53 51 49 9db508e5-9143-4cc1-a9a5-177237180d0b
45 35 31 28 25 22 20 18 16 14 35d897f0-c1b4-422c-9a33-43e7da1ffe27
128 107 92 75 64 60 55 52 48 45 41 38 35 30 28 26 24 22 20 18 16 14 12 10 06cdfa3d-8d45-4fe3-85c8-505e1b1b4de2
36 29 24 20 18 16 14 186141c9-4307-4068-adc7-616b1f8c5e0a
23 15 12 10 8 945f0e58-761c-4c89-af96-0261821fcf11
30 13 10 8 6 4 c7fac934-2a4b-49f0-b20b-568bb11557f2
21 13 11 9 fabdb7c1-5afb-45cb-b0d2-dce923889ea8
163 53 48 41 37 34 32 30 28 26 24 22 06908246-ff47-414c-9db2-77df83e43aee
18 11 9 afdd3dad-858c-46e7-972e-d5909efbe9ce
99 87 78 69 60 57 53 50 47 45 43 41 39 37 354d95b7-42b8-4e01-be2e-039149095d2d
108 68 48 39 32 29 25 23 21 19 17 15 13 d1070d87-7bcb-4325-94b7-fc8370bd6ed5
23 19 17 15 13 11 4b331fd2-8e92-4f74-90cd-615d90694463
34 22 19 16 14 12 9f29fc63-85b9-4959-bb7e-dd3f169b862d
110 74 67 58 52 48 45 42 40 36 34 32 30 f97dc224-8c40-4a1e-be11-d71eeca0c510
133 24 22 19 17 15 13 ecc59e41-4029-4d09-9a50-fb997d4daf0e
138 106 97 93 89 84 81 77 74 69 67 65 62 60 58 56 54 52 49 47 45 43 41 39 b470d591-dc0c-41e1-afa7-4f212d6248e5
116 17 12 10 8 6 0680d727-2e00-45e2-8ebc-0eea81f20937
90 66 54 49 45 39 36 33 31 29 27 25 23 21 19 dad43e50-3167-41d6-996c-5b6e5f200c07
182 92 81 72 66 61 56 52 48 44 42 40 38 36 34 32 30 a400cdc0-ed2f-4adf-928d-816320717a92
29 14 12 10 8 0235896f-1570-418a-a34d-7bc3ea0f82b9
75 67 60 55 49 46 44 42 40 38 36 2dd5c077-0f51-41b0-9da0-0b59eb3328c3
133 54 47 44 41 37 35 33 31 c51b89a6-0219-4eee-bb89-b2b5168998f5
147 121 113 107 100 97 94 91 88 85 82 80 78 76 72 70 68 66 64 62 60 58 56 54 52 50 48 46 509987fb-fce6-4d2f-98b8-bb4ba3761aae
18 10 6 4 0a8e8837-0a58-4e89-96c2-c44ae7281535
104 22 15 13 11 9 7 5 3 bd121004-afeb-4447-bb77-978e7502baa3
38 29 23 19 17 15 b1a78d64-0171-4180-b564-1172fbb92608
171 154 147 140 133 127 121 116 111 107 104 101 99 94 92 90 88 86 84 82 80 76 74 72 70 68 66 64 62 60 58 cfb7ac32-173c-4a66-9ee0-771a20eb93ed
36 22 20 16 14 8c1bd275-6ae7-4fd2-a2fb-8a965af31699
50 34 29 25 22 19 17 fcf5ff56-5e98-4eb7-8df3-afb0544d9739
97 84 75 65 59 54 49 45 42 39 36 34 32 28 26 24 22 20 18 16 4ca6cd4c-9b4a-4226-89ec-14a4d8621968
139 115 96 83 75 69 63 60 58 56 54 52 50 48 46 44 42 40 38 36 34 18fab27c-7420-4b80-a5b4-cce94a9c315c
100 40 38 35 33 31 29 27 25 23 21 2f551477-6bc3-42bf-bee6-493eb83a8923
21 11 7 4 2 e5e2e91d-9054-4996-a3bf-62518e06a07f
15 4 2 0f235f9a-64f8-4790-917d-23e0a15077c5
108 90 70 62 56 50 46 44 42 39 37 35 33 31 29 27 25 23 21 19 17 c8ee61ed-aa7c-44da-a43d-f862fa5cce8d
40 30 26 24 22 20 18 16 920df344-fe5c-4f48-ae64-a8458e8db40a
74 61 53 45 39 37 34 32 29 27 25 23 21 49441f3e-1d4b-4b06-9cd3-b6669884c2df
36 22 18 15 11 9 87ab08a3-0acb-4f5b-b1c8-927bb83c3842
92 50 42 39 36 34 32 30 28 26 3a3b57d9-5af7-4515-9347-2cc1f91ffae1
66 61 57 53 49 46 43 41 39 37 35 33 31 29 27 25 23 21 72089129-da8d-4f2c-91ee-6ec1410a2721
18 10 7 5 3 ea3f9eac-c1d2-4bbc-8271-46786e9ccd20
109 88 76 66 63 60 57 54 51 49 47 45 6e79e7db-57b6-444a-8cbc-a000932c6de8
74 63 54 48 44 41 38 35 33 31 29 27 25 23 1ed16c88-ff9d-488c-be13-6ba2be1d1cc0
101 87 81 76 71 67 64 60 57 55 53 50 48 46 44 42 40 37 35 33 31 e71649c1-57e4-4cf6-a5fe-c55b8568add3
135 118 112 106 101 97 92 87 84 81 78 76 74 72 70 67 65 63 61 59 57 55 40c10a59-eeab-4673-b943-69e501cfef5f
93 47 29 26 23 21 52f6e329-eea6-423b-8d6a-047448d02c3f
42 37 29 25 22 20 3d62bda8-dc02-47aa-ae1e-dc0f5e2aef1b
153 146 134 128 122 117 113 109 105 102 98 94 90 88 85 82 80 77 75 73 71 69 67 65 63 59 57 55 53 b835a560-6e0a-4dc2-a661-ce64a7d4eb39
85 72 64 60 55 52 49 47 45 43 41 39 37 35 33 31 29 27 b85b1a95-35ba-473e-a164-4602a4a13a2f
120 115 94 83 76 72 68 64 60 57 55 53 51 49 47 43 41 66703b48-f3b2-4853-82a0-00ba13379012
143 110 101 95 90 85 82 78 73 69 66 64 62 60 57 53 50 48 46 44 42 7e18c9c0-462a-4865-be25-1dd992b8af9f
82 57 49 45 41 38 36 34 32 30 28 26 24 22 20 18 c7a2c75a-980f-43c9-8366-490060bb7627
47 40 33 27 20 16 14 c405c4a8-83f2-4ddf-b0cf-941a3356b251
117 48 21 16 12 10 8 6 1e0b7fa1-1947-40eb-9ffa-b2a46853da49
148 100 80 67 55 49 45 42 39 36 33 30 28 26 24 22 20 5005b73d-b6bd-499c-8d6f-554785c4e523
40 35 31 28 26 24 22 20 18 16 14