# Applicator

I want to apply a theory to a response. In principle, the response should just be a sentence, but it needs to have been read and SpaCy'd first. So for the moment, I'll just assume that we're applying to sentences from the data file. Which, fortunately, is all encoded in the theory object, having been extracted from `bea_2way_data_pickle`.

Want two outputs: one of the results, one of the applications.

The theory itself will be the output from `bea_2way_theory_generator.ipynb/induce_theory`.

Want `apply_theory(theory, original_response_id)`.

Actually, a better plan might be to just have a function which applies the theory to the embedded trial set.

`apply_trial_set(theory)`

In [212]:
THEORY_ROOT_DIR='/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318'

In [213]:
import amati_bea as amati

In [214]:
import pandas as pd

from sklearn.metrics import f1_score, cohen_kappa_score

In [215]:
from operator import itemgetter
import pickle
import datetime
import re
import os
import glob

## Get the data

We'll just be able to pull out the relevant data from the saved theory.

In [216]:
with open(
    "/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260316/theory_0a8e8837-0a58-4e89-96c2-c44ae7281535_2026-03-16_21:09:29.557897.pickle", "rb"
) as fIn:
    theory = pickle.load(fIn)

In [217]:
theory.keys()

dict_keys(['theory', 'original_question_id', 'question_id', 'all_questions_df', 'all_responses_df', 'all_text_df', 'rules'])

Let's find a trial response. First, need to pull out the question for that theory:

In [218]:
theory["question_id"]

'q_05'

And then get the associated responses:

In [219]:
theory["all_responses_df"].query("`question_id`==@theory['question_id']").query(
    "`partition`=='trial'"
).head()

,original_response_id,response_id,question_id,response,score,partition
865,04a4fee4-1dab-48d2-903b-a4159319d652,r_0006,q_05,"Es fällt auf , dass nachdem die Buntbarsche ei...",incorrect,trial
866,af488940-639d-4bec-bab0-15717b25c829,r_0150,q_05,Fisch nummer 4 passt zu den Beobachtung wenig ...,incorrect,trial
867,e38ceb02-4d7a-4558-9582-3e55b0710eba,r_0683,q_05,"In den ersten 6 Monaten , stieg die Anzahl und...",correct,trial
868,f0f4ffc7-bedf-451a-83e7-10a855903d60,r_1527,q_05,bis zum 6. Monat sich die Flecken in beiden Be...,incorrect,trial
869,101e8fe2-9e9c-4216-928a-83d0a33bddbb,r_1723,q_05,In den Becken mit groben Kies und ohne Buntbar...,incorrect,trial

So let's just bag the first of those:

In [220]:
TEST_RESPONSE_ID = (
    theory["all_responses_df"]
    .query("`question_id`==@theory['question_id']")
    .query("`partition`=='trial'")
    .iloc[0, 0]
)

TEST_RESPONSE_ID

'04a4fee4-1dab-48d2-903b-a4159319d652'

Reverse ferret, let's apply to the trial set:

In [221]:
def apply_trial_set(theory):

    question_id=theory["question_id"]
    original_question_id=theory["original_question_id"]

    question_ss = theory['all_questions_df'].set_index("original_question_id").T[
        original_question_id
    ]
    
    trial_responses_df = theory['all_responses_df'].query("`question_id`==@question_id").query(
        "`partition`=='trial'"
    )

    trial_texts_used = [
        question_id,
        question_ss["correct_id"],
        question_ss["incorrect_1_id"],
        question_ss["incorrect_2_id"],
    ] + list(trial_responses_df["response_id"])

    trial_text_df = theory['all_text_df'].query("`id`.isin(@trial_texts_used)")[
        ["id", "i", "lemma"]
    ]

    results_df = amati.evaluate_theory(
        theory['theory'],
        responses_df=trial_responses_df,
        text_df=trial_text_df,
        rulesstring=theory['rules'],
        question_ss=question_ss,
    )

    compare_df = (
        trial_responses_df[["response_id", "score"]]
        .rename({"score": "actual"}, axis="columns")
        .set_index("response_id")
        .assign(
            prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")
        )
    )

    return {"theory": theory, "results": results_df, "compare": compare_df}

In [222]:
def get_rule_applications(theory):

    question_id=theory["question_id"]
    original_question_id=theory["original_question_id"]

    question_ss = theory['all_questions_df'].set_index("original_question_id").T[
        original_question_id
    ]
    
    trial_responses_df = theory['all_responses_df'].query("`question_id`==@question_id").query(
        "`partition`=='trial'"
    )

    trial_texts_used = [
        question_id,
        question_ss["correct_id"],
        question_ss["incorrect_1_id"],
        question_ss["incorrect_2_id"],
    ] + list(trial_responses_df["response_id"])

    trial_text_df = theory['all_text_df'].query("`id`.isin(@trial_texts_used)")[
        ["id", "i", "lemma"]
    ]

    results_dict = amati.apply_theory(
        theory['theory'],
        responses_df=trial_responses_df,
        text_df=trial_text_df,
        rulesstring=theory['rules'],
        question_ss=question_ss,
    )

    """ compare_df = (
        trial_responses_df[["response_id", "score"]]
        .rename({"score": "actual"}, axis="columns")
        .set_index("response_id")
        .assign(
            prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")
        )
    ) """

    return {"theory": theory, "applications": results_dict}

In [223]:
question_id = theory["question_id"]
original_question_id = theory["original_question_id"]

question_ss = (
    theory["all_questions_df"].set_index("original_question_id").T[original_question_id]
)

trial_responses_df = (
    theory["all_responses_df"]
    .query("`question_id`==@question_id")
    .query("`partition`=='trial'")
)

trial_texts_used = [
    question_id,
    question_ss["correct_id"],
    question_ss["incorrect_1_id"],
    question_ss["incorrect_2_id"],
] + list(trial_responses_df["response_id"])

trial_text_df = theory["all_text_df"].query("`id`.isin(@trial_texts_used)")[
    ["id", "i", "lemma"]
]


d=apply_theory(
    theory["theory"],
    responses_df=trial_responses_df,
    rulesstring=theory["rules"],
    question_ss=question_ss,
    text_df=trial_text_df,
)
d

In [224]:

amati.apply_theory(
    theory["theory"],
    responses_df=trial_responses_df,
    rulesstring=theory["rules"],
    question_ss=question_ss,
    text_df=trial_text_df,
)

{'r_0006': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_0150': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_0683': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_1527': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_1723': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_1881': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_3258': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',

In [225]:
o=apply_trial_set(theory)

In [226]:
o['results']

                     0        1    2    3    4    5    6    7
response_id
r_0006       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_0150       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_0683       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_1527       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_1723       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_1881       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_3258       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_3716       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_4192             NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_6232       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN
r_6306       incorrect  correct  NaN  NaN  NaN  NaN  NaN  NaN
r_6781       incorrect      NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [227]:
t=get_rule_applications(theory)
t['applications']

{'r_0006': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_0150': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_0683': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_1527': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_1723': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_1881': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',
    'r_5446',
    'r_5748',
    'r_7718',
    'r_7802',
    'r_7896'],
   'evaluations': {'precision': 82,
    'compression': 63,
    'coverage': 65,
    'accuracy': 82},
   'positive_df':     response_id question_id      score  covered
   0        r_0118        q_05    correct    False
   1        r_0217        q_05    correct    False
   2        r_0221        q_05  incorrect     True
   3        r_0358        q_05  incorrect     True
   4        r_0715        q_05  incorrect     True
   ..          ...         ...        ...      ...
   99       r_7718        q_05    correct    False
   100      r_7754        q_05  incorrect     True
   101      r_7802        q_05    correct    False
   102      r_7891        q_05  incorrect     True
   103      r_7896        q_05    correct    False

   [104 rows x 4 columns],
   'negative_df':     response_id question_id      score  covered
   0        r_0118        q_05  incorrect     True
   1        r_0217        q_05  incorrect     True
   2        r_0221        q_05    correct    False
   3        r_0358        q_05    correct    False
   4        r_0715        q_05    correct    False
   ..          ...         ...        ...      ...
   99       r_7718        q_05  incorrect     True
   100      r_7754        q_05    correct    False
   101      r_7802        q_05  incorrect     True
   102      r_7891        q_05    correct    False
   103      r_7896        q_05  incorrect     True

   [104 rows x 4 columns]}],
 'r_3258': [{'result': 'SATISFIABLE',
   'selected_rule': ('ki_rule1', 'selected_rule(ki_rule1)'),
   'predicted_grade': ('incorrect', 'predicted_grade(incorrect)'),
   'parameters': [(1, '"zwanzig"', 'parameter(1,"zwanzig")')],
   'positive_covered': ['r_0221',
    'r_0358',
    'r_0715',
    'r_0720',
    'r_0880',
    'r_0999',
    'r_1487',
    'r_1554',
    'r_1776',
    'r_1809',
    'r_1820',
    'r_1827',
    'r_1832',
    'r_1853',
    'r_1897',
    'r_1977',
    'r_2117',
    'r_2147',
    'r_2269',
    'r_2946',
    'r_2949',
    'r_3044',
    'r_3162',
    'r_3165',
    'r_3228',
    'r_3243',
    'r_3246',
    'r_3313',
    'r_3361',
    'r_3462',
    'r_3542',
    'r_3602',
    'r_3665',
    'r_3874',
    'r_4311',
    'r_4370',
    'r_4415',
    'r_4501',
    'r_4524',
    'r_4643',
    'r_4679',
    'r_4847',
    'r_4881',
    'r_4997',
    'r_5116',
    'r_5291',
    'r_5536',
    'r_5575',
    'r_5756',
    'r_5774',
    'r_5906',
    'r_5907',
    'r_5924',
    'r_5936',
    'r_6085',
    'r_6142',
    'r_6168',
    'r_6219',
    'r_6403',
    'r_6434',
    'r_6436',
    'r_6503',
    'r_6514',
    'r_6541',
    'r_6551',
    'r_6671',
    'r_6704',
    'r_6874',
    'r_6904',
    'r_6987',
    'r_7049',
    'r_7070',
    'r_7188',
    'r_7193',
    'r_7246',
    'r_7259',
    'r_7284',
    'r_7596',
    'r_7618',
    'r_7649',
    'r_7754',
    'r_7891'],
   'negative_covered': ['r_0118',
    'r_0217',
    'r_1411',
    'r_2360',
    'r_2515',
    'r_3541',
    'r_3590',
    'r_3931',
    'r_4228',
    'r_4978',
    'r_5091',
    'r_5333',

t['applications']['r_1842']

## Apply to all theories

In [228]:
outputs_ls=[]

for f in glob.glob(os.path.join(THEORY_ROOT_DIR, '*')):
    print(f)
    with open(f, 'rb') as fIn:
        try:
            theory=pickle.load(fIn)
            outputs_ls.append(apply_trial_set(theory))
        except:
            continue

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_5f7bd982-606b-45e4-bf39-89db6714a621_2026-03-18_12:52:28.028319.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_35d897f0-c1b4-422c-9a33-43e7da1ffe27_2026-03-18_12:57:35.168998.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_52f6e329-eea6-423b-8d6a-047448d02c3f_2026-03-18_15:45:58.021429.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_c405c4a8-83f2-4ddf-b0cf-941a3356b251_2026-03-18_16:59:35.923009.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_0235896f-1570-418a-a34d-7bc3ea0f82b9_2026-03-18_14:07:56.575271.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_920df344-fe5c-4f48-ae64-a8458e8db40a_2026-03-18_15:24:00.591946.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_c51b89a6-0219-4eee-bb89-b2b5168998f5_2026-03-18_14:12:46.706850.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_0f036c26-4a47-48ba-b913-f27487286ac7_2026-03-18_12:23:14.044820.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_48071573-9e44-4ae9-b08c-2b19b6ee58d6_2026-03-18_12:27:26.893725.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_dad43e50-3167-41d6-996c-5b6e5f200c07_2026-03-18_13:59:21.119527.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_b85b1a95-35ba-473e-a164-4602a4a13a2f_2026-03-18_16:01:01.534496.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_0f235f9a-64f8-4790-917d-23e0a15077c5_2026-03-18_15:10:43.190962.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_0a8e8837-0a58-4e89-96c2-c44ae7281535_2026-03-18_14:24:05.896976.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_7e18c9c0-462a-4865-be25-1dd992b8af9f_2026-03-18_16:57:11.013936.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_dddf3a9d-2f40-402c-b650-3db1b27128ca_2026-03-18_11:29:58.119982.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_40c10a59-eeab-4673-b943-69e501cfef5f_2026-03-18_15:45:23.476327.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_b835a560-6e0a-4dc2-a661-ce64a7d4eb39_2026-03-18_15:58:28.407989.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_8144573c-97d6-484a-b68b-c16b7602fa7b_2026-03-18_12:23:52.124474.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_8a35dfaf-e9d0-466d-98b8-1e1b132bb450_2026-03-18_11:51:36.602801.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_509987fb-fce6-4d2f-98b8-bb4ba3761aae_2026-03-18_14:24:04.896227.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_e6f0fdac-98cd-4ad5-a700-cb612f4ec827_2026-03-18_12:27:28.261676.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_b470d591-dc0c-41e1-afa7-4f212d6248e5_2026-03-18_13:51:54.370637.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_6e79e7db-57b6-444a-8cbc-a000932c6de8_2026-03-18_15:36:12.590240.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_c7fac934-2a4b-49f0-b20b-568bb11557f2_2026-03-18_13:15:38.448888.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_fcf5ff56-5e98-4eb7-8df3-afb0544d9739_2026-03-18_14:50:08.760170.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_18fab27c-7420-4b80-a5b4-cce94a9c315c_2026-03-18_15:08:16.884805.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_bd121004-afeb-4447-bb77-978e7502baa3_2026-03-18_14:28:02.530386.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_b1d2b0f3-f2d0-4be0-850f-1b7810acd965_2026-03-18_12:52:40.162293.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_afdd3dad-858c-46e7-972e-d5909efbe9ce_2026-03-18_13:20:13.076013.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_0680d727-2e00-45e2-8ebc-0eea81f20937_2026-03-18_13:54:34.856759.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_dee4136e-e922-4b83-8033-24350ea1610c_2026-03-18_11:27:33.266979.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_72089129-da8d-4f2c-91ee-6ec1410a2721_2026-03-18_15:33:35.192035.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_3a3b57d9-5af7-4515-9347-2cc1f91ffae1_2026-03-18_15:33:20.253526.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_1ed16c88-ff9d-488c-be13-6ba2be1d1cc0_2026-03-18_15:37:44.100306.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_c8ee61ed-aa7c-44da-a43d-f862fa5cce8d_2026-03-18_15:23:50.641008.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_9db508e5-9143-4cc1-a9a5-177237180d0b_2026-03-18_12:55:40.852222.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_66703b48-f3b2-4853-82a0-00ba13379012_2026-03-18_16:35:04.523980.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_b1a78d64-0171-4180-b564-1172fbb92608_2026-03-18_14:28:08.330725.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_ea3f9eac-c1d2-4bbc-8271-46786e9ccd20_2026-03-18_15:33:37.379697.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_b5fb6924-1da3-45b1-a386-68e95d80b057_2026-03-18_11:31:36.394397.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_b3978794-9681-49bd-bc9b-d05bf8d226d8_2026-03-18_12:41:49.994256.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_06cdfa3d-8d45-4fe3-85c8-505e1b1b4de2_2026-03-18_13:15:30.479275.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_354d95b7-42b8-4e01-be2e-039149095d2d_2026-03-18_13:30:38.402370.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_c7a2c75a-980f-43c9-8366-490060bb7627_2026-03-18_16:59:30.187875.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_d9e775ff-b54e-4558-86eb-0251737ecdf1_2026-03-18_12:20:40.548977.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_33c179c8-ee50-4a7b-b139-8b2984356400_2026-03-18_11:44:18.973122.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_1e0b7fa1-1947-40eb-9ffa-b2a46853da49_2026-03-18_17:04:21.994564.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_2f551477-6bc3-42bf-bee6-493eb83a8923_2026-03-18_15:10:41.338008.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_9f29fc63-85b9-4959-bb7e-dd3f169b862d_2026-03-18_13:33:24.917069.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_e5e2e91d-9054-4996-a3bf-62518e06a07f_2026-03-18_15:10:42.491262.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_8e686080-6db7-473b-baa0-6f17412fae5c_2026-03-18_11:20:01.490557.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_3d62bda8-dc02-47aa-ae1e-dc0f5e2aef1b_2026-03-18_15:46:04.179595.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_cb99dfb3-2788-4a10-b934-7ea8276b2b44_2026-03-18_12:30:33.458041.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_87ab08a3-0acb-4f5b-b1c8-927bb83c3842_2026-03-18_15:29:21.590975.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_11be53c7-c020-445b-b3a4-409d4ba16347_2026-03-18_12:52:29.386678.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_d1070d87-7bcb-4325-94b7-fc8370bd6ed5_2026-03-18_13:33:21.159020.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_d14cc74c-805a-45f7-9ad3-2e9f19395ca0_2026-03-18_12:20:42.521643.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_e71649c1-57e4-4cf6-a5fe-c55b8568add3_2026-03-18_15:39:10.296408.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_a400cdc0-ed2f-4adf-928d-816320717a92_2026-03-18_14:07:47.316985.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_82aacab8-0c7f-4936-b93f-62c53670b5c3_2026-03-18_12:44:13.611688.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_bbb0e987-436a-46f3-b16d-34fd708f8236_2026-03-18_12:52:27.159972.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_4b331fd2-8e92-4f74-90cd-615d90694463_2026-03-18_13:33:23.013609.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_945f0e58-761c-4c89-af96-0261821fcf11_2026-03-18_13:15:34.001010.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_f97dc224-8c40-4a1e-be11-d71eeca0c510_2026-03-18_13:40:07.411481.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_06908246-ff47-414c-9db2-77df83e43aee_2026-03-18_13:20:12.327352.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_379ba896-bb8f-440d-9d32-5dc9ca0297fe_2026-03-18_12:25:21.835522.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_64636904-aab6-4e10-a4dc-39638117731a_2026-03-18_11:17:53.999799.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_cfb7ac32-173c-4a66-9ee0-771a20eb93ed_2026-03-18_14:49:52.922613.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_1f2f0773-54bb-4b72-963e-c3c946a1f53f_2026-03-18_12:52:44.298408.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_fabdb7c1-5afb-45cb-b0d2-dce923889ea8_2026-03-18_13:15:39.412569.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_2dd5c077-0f51-41b0-9da0-0b59eb3328c3_2026-03-18_14:08:25.734410.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_8c1bd275-6ae7-4fd2-a2fb-8a965af31699_2026-03-18_14:49:55.228603.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_186141c9-4307-4068-adc7-616b1f8c5e0a_2026-03-18_13:15:32.839393.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_49441f3e-1d4b-4b06-9cd3-b6669884c2df_2026-03-18_15:29:05.455371.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_ecc59e41-4029-4d09-9a50-fb997d4daf0e_2026-03-18_13:42:33.757542.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_4ca6cd4c-9b4a-4226-89ec-14a4d8621968_2026-03-18_14:53:48.872391.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_5005b73d-b6bd-499c-8d6f-554785c4e523_2026-03-18_17:11:02.519717.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_278f349f-1552-41c4-bec2-1de41838f229_2026-03-18_11:44:25.251416.pickle

/var/folders/ql/c79k160s5zjd1mzy_k08xvc40000gq/T/ipykernel_23082/2063899696.py:38: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")

And now we should be able to get an overall assessment...

In [229]:
outputs_ls[1]['results']

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
response_id,,,,,,,,,,,,,,,,,,,,,
r_0301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_0349,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_0364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,correct,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_0713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_1842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_1948,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_4050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,incorrect,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_4627,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,incorrect,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_5119,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_5382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_5714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_5894,NaN,NaN,NaN,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_6439,NaN,NaN,NaN,NaN,NaN,correct,NaN,incorrect,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_6578,NaN,NaN,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_7564,NaN,NaN,correct,NaN,NaN,NaN,NaN,incorrect,NaN,NaN,...,NaN,NaN,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN

In [230]:
outputs_ls[2]['results']

               0        1    2    3          4
response_id
r_2525       NaN  correct  NaN  NaN        NaN
r_2583       NaN      NaN  NaN  NaN        NaN
r_3980       NaN      NaN  NaN  NaN  incorrect
r_6008       NaN  correct  NaN  NaN        NaN
r_7624       NaN  correct  NaN  NaN        NaN

First, get a big table of all the predictions:

In [231]:
predictions_df=pd.concat([o['results'] for o in outputs_ls])
predictions_df

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
response_id,,,,,,,,,,,,,,,,,,,,,
r_0260,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_2226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_2713,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_3728,incorrect,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_6429,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
r_5178,NaN,NaN,NaN,NaN,incorrect,NaN,NaN,correct,NaN,incorrect,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_5265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_5328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_6417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_6682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [232]:
# Let's define an ordered category for the prediction:

prediction_type = pd.CategoricalDtype(
    categories=['incorrect',  'correct'],
    ordered=True
)
prediction_type

CategoricalDtype(categories=['incorrect', 'correct'], ordered=True, categories_dtype=object)

And we can use this type on the predictions DataFrame:

In [233]:
predictions_df=predictions_df.astype(prediction_type)
predictions_df.head()

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
response_id,,,,,,,,,,,,,,,,,,,,,
r_0260,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_2226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_2713,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_3728,incorrect,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_6429,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now, an interesting comparison might be whether we choose the first prediction or the last prediction. ie. Do later predictions override the earlier ones, or should the first prediction stand?

In [234]:
predict_first_ss=predictions_df.bfill(axis='columns').iloc[:, 0].fillna('incorrect')
predict_first_ss

response_id
r_0260    incorrect
r_2226    incorrect
r_2713    incorrect
r_3728    incorrect
r_6429    incorrect
            ...
r_5178    incorrect
r_5265    incorrect
r_5328    incorrect
r_6417    incorrect
r_6682    incorrect
Name: 0, Length: 827, dtype: category
Categories (2, object): ['incorrect' < 'correct']

In [235]:
predict_last_ss=predictions_df.ffill(axis='columns').iloc[:, -1].fillna('incorrect')
predict_last_ss

response_id
r_0260    incorrect
r_2226    incorrect
r_2713    incorrect
r_3728    incorrect
r_6429    incorrect
            ...
r_5178    incorrect
r_5265    incorrect
r_5328    incorrect
r_6417    incorrect
r_6682    incorrect
Name: 33, Length: 827, dtype: category
Categories (2, object): ['incorrect' < 'correct']

And now we need to do a comparison with the ground truth results.

In [236]:
results_df = (
    theory["all_responses_df"]
    .query("`partition`=='trial'")
    .set_index("response_id")[["score"]]
    .rename({"score": "actual"}, axis="columns")
    .astype(prediction_type)
    .assign(predict_first=predict_first_ss, predict_last=predict_last_ss)
)

results_df

                actual predict_first predict_last
response_id
r_1565       incorrect     incorrect    incorrect
r_2712       incorrect       correct      correct
r_2987       incorrect     incorrect    incorrect
r_3994       incorrect     incorrect    incorrect
r_4566       incorrect     incorrect    incorrect
...                ...           ...          ...
r_7743         correct     incorrect    incorrect
r_1396       incorrect     incorrect    incorrect
r_4071       incorrect     incorrect    incorrect
r_6273       incorrect     incorrect    incorrect
r_6877       incorrect     incorrect    incorrect

[827 rows x 3 columns]

In [237]:
results_df.query('`predict_first`!=`predict_last`')

                actual predict_first predict_last
response_id
r_3735         correct     incorrect      correct
r_4164         correct       correct    incorrect
r_6282       incorrect     incorrect      correct
r_7104         correct     incorrect      correct
r_5923         correct     incorrect      correct
r_7703       incorrect     incorrect      correct
r_6980       incorrect       correct    incorrect
r_6306       incorrect     incorrect      correct
r_4058       incorrect     incorrect      correct
r_1103         correct       correct    incorrect
r_1766         correct       correct    incorrect
r_1864       incorrect     incorrect      correct
r_3489       incorrect     incorrect      correct
r_6897         correct       correct    incorrect
r_0430       incorrect     incorrect      correct
r_1283         correct       correct    incorrect
r_3766         correct       correct    incorrect
r_5371         correct     incorrect      correct
r_1308       incorrect       correct    incorrect
r_4163       incorrect     incorrect      correct
r_4588         correct     incorrect      correct
r_5699         correct     incorrect      correct
r_0710         correct       correct    incorrect
r_3972         correct       correct    incorrect
r_6630       incorrect     incorrect      correct
r_5424         correct       correct    incorrect
r_5193         correct       correct    incorrect
r_0922         correct       correct    incorrect
r_5689       incorrect     incorrect      correct
r_6456         correct       correct    incorrect
r_7749       incorrect     incorrect      correct
r_7239       incorrect     incorrect      correct
r_5263       incorrect       correct    incorrect
r_6439         correct       correct    incorrect
r_7564         correct       correct    incorrect

In [238]:
results_df.dropna()

                actual predict_first predict_last
response_id
r_1565       incorrect     incorrect    incorrect
r_2712       incorrect       correct      correct
r_2987       incorrect     incorrect    incorrect
r_3994       incorrect     incorrect    incorrect
r_4566       incorrect     incorrect    incorrect
...                ...           ...          ...
r_7743         correct     incorrect    incorrect
r_1396       incorrect     incorrect    incorrect
r_4071       incorrect     incorrect    incorrect
r_6273       incorrect     incorrect    incorrect
r_6877       incorrect     incorrect    incorrect

[827 rows x 3 columns]

In [239]:
f1_score(results_df.dropna()['actual'], results_df.dropna()['predict_first'], average='weighted')

0.7802638597361653

In [240]:
f1_score(results_df.dropna()['actual'], results_df.dropna()['predict_last'], average='weighted')

0.7586604680256408

OK, predict first seems slightly better, as expected, although they're both pretty dire. Now let's do the evaluation with CWK:

In [241]:
cohen_kappa_score(results_df.dropna()['actual'], results_df.dropna()['predict_first'], weights='quadratic')

0.4527227061814777

That's hardly going to set the world alight...